baseURL = "https://eyeofparadox.github.io/"
languageCode = "en-us"
title = "eyeofparadox.com [eyeofparadox.wordpress.com] to eyeofparadox.github.io"
theme = "github-style"

# Optional: enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

# Taxonomies
[taxonomies]
	category = "categories"
	tag = "tags"

# Params specific to GitHub-Style
[params]
	author = "David Bryan Roberson"
	description = "blog, echo, wordpress, posts, pages, essays, articles, fiction"
	github = "eyeofparadox"
	twitter = "EyeOfParadox"

# Markup configuration
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

	[markup.highlight]
		codeFences = true
		guessSyntax = true
		lineNos = true

# Optional: suppress warnings if you prefer a clean build log
ignoreLogs = ['warning-goldmark-raw-html']
