# hugo.toml
# 	ref: theme.toml Hugo theme template
# 	See https://github.com/gohugoio/hugoThemesSiteBuilder
# 	source for https://themes.gohugo.io

baseURL = "https://eyeofparadox.github.io/"
languageCode = "en-us"
title = "eyeofparadox.com [eyeofparadox.wordpress.com] to eyeofparadox.github.io"
theme = "github-style"

# [author]
  # name = "eyeofparadox"
  # homepage = "https://github.com/eyeofparadox"
  
# Optional: enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

# Taxonomies
[taxonomies]
	category = "categories"
	tag = "tags"

# Params specific to GitHub-Style
[params]
	author = "eyeofparadox"
	url = "https://github.com/eyeofparadox"

	description = "in the ashes of ideas hides the spark of understanding"
	keywords = "blog, echo, wordpress, posts, pages, essays, articles, fiction"
	github = "eyeofparadox"
	wordpress = "eyeofparadox"
	artstation = "davidbryanroberson"
	fab = "davidbryanroberson"
	sketchfab = "davidbryanroberson"
	deviantart = "aeirn"
	pinterest = "davidbroberson"
	instagram = "davidbryanroberso"
	tumblr = "davidbroberson"
	twitter = "EyeOfParadox"

# Markup configuration
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

	[markup.highlight]
		codeFences = true
		guessSyntax = true
		lineNos = true

# Optional: suppress warnings if you prefer a clean build log
ignoreLogs = ['warning-goldmark-raw-html']
